import type { Metadata } from 'next';
import '../styles/globals.css';
import { Inter as FontSans } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Theme, ThemePanel } from '@radix-ui/themes';
import { cn } from '../lib/utils';
import { CustomHeader } from '@/features/CustomHeader';
import Sidebar from '@/features/Sidebar';
import { AuthContextProvider } from '@/context/AuthContext';
import { ReactNode } from 'react';
import { Toaster } from '@/components/ui/toaster';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body
        className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange
        >
          <Theme>
            <AuthContextProvider>
              <div className='relative z-0 flex h-full w-full overflow-hidden'>
                <Sidebar />
                <div className='w-screen'>
                  <CustomHeader name={'satoki'} />
                  <div className='container'>{children}</div>
                  <Toaster />
                </div>
              </div>
            </AuthContextProvider>
            {/* <ThemePanel /> */}
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
