name: 'CI pipeline for develop branch'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: 'yarn'

      - name: Install Packages
        run: yarn install

      - name: Get list of changed files
        id: changed-files
        run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 'src/**/*.ts' 'src/**/*.tsx' 'src/**/*.js' 'src/**/*.jsx')" >> $GITHUB_ENV

      - name: Debug changed files
        run: echo "Changed Files - $CHANGED_FILES "

      - name: Run prettier for changed files
        # if: env.CHANGED_FILES != ''
        # run: yarn prettier --check --list-diff ${{ env.CHANGED_FILES }}
        run: yarn format:check

      - name: ESlint
        run: yarn lint --cache --quiet

      - name: TypeScript Compiler
        run: yarn tsc --noEmit

      - name: Build Check
        run: yarn build
